services:
  postgres:
    image: postgres:16-alpine
    container_name: saas-licitacao-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: saas
      POSTGRES_PASSWORD: saas123
      POSTGRES_DB: saas_licitacao
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
